#!/usr/bin/env bash
# script that displays info about subdomains

print_subdomains()
{
    result=$(dig "$2"."$1" +noall +answer)
    echo "$result $2" | awk -F' ' '{ print "The subdomain " $6 " is a " $4 " record and points to " $5}'
}

if [ -z "$2" ];
then
    for sub_doms in "www" "lb-01" "web-01" "web-02"
    do
        print_subdomains "$1" "$sub_doms"
    done
else
    print_subdomains "$1" "$2"
fi