#!/usr/bin/env bash
# transfers a file from one server to another
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit
else
	pathfile=$1
	ip=$2
	username=$3
	pathtossh=$4
	scp "StrictHostKeyChecking=no" "$1" "$3"@"$2":"$4"
fi
