#!/usr/bin/env bash
# install nginx server in our server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service start nginx


