#!/usr/bin/env bash
# install nginx server in our server
string_n="\\\trewrite ^/redirect_me(.*)$ https://example.com;\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "48i $string_n" /etc/nginx/sites-available/default
sudo service nginx start
