#!/usr/bin/env bash
# install nginx server in our server
string_n="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "48i $string_n" /etc/nginx/sites-available/default
sudo service nginx restart
