#!/usr/bin/env bash
# install HAproxy as load balancer
# configure the load balancer to serve our servers
# distribute requests using roundrobin algo
# to send traffic to both web-01 and web-02

sudo apt-get update -y

#install load balancer
sudo apt-get install -y haproxy
#init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

#back up copy of default config file
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

#edit haproxy config
sudo echo -e "
global
\tlog 54.236.56.164 local0 notice
\tmaxconn 2000
\tuser haproxy
\tgroup haproxy
defaults
\tlog     global
\tmode    http
\toption  httplog
\toption  dontlognull
\tretries 3
\toption redispatch
\ttimeout connect  5000
#!/usr/bin/env bash
# install HAproxy as load balancer
# configure the load balancer to serve our servers
# distribute requests using roundrobin algo
# to send traffic to both web-01 and web-02

sudo apt-get update -y

#install load balancer
sudo apt-get install -y haproxy
#init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

#back up copy of default config file
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

#edit haproxy config
sudo echo -e "
global
\tlog 54.236.56.164 local0 notice
\tmaxconn 2000
\tuser haproxy
\tgroup haproxy
defaults
\tlog     global
\tmode    http
\toption  httplog
\toption  dontlognull
\tretries 3
\toption redispatch
\ttimeout connect  5000
\ttimeout client  10000
\ttimeout server  10000
listen appname
\tbind :80
\tmode http
\tstats enable
\tstats uri /haproxy?stats
\tbalance roundrobin
\toption httpclose
\toption forwardfor
\tserver 107478-web-01 54.236.56.164:80 check
\tserver 107478-web-02 54.90.17.105:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

#verify config syntax of the configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart

