#!/usr/bin/env bash
# install HAproxy as load balancer
# configure the load balancer to serve our servers
# distribute requests using roundrobin algo
# to send traffic to both web-01 and web-02

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get update -y

#install load balancer
sudo apt-get install -y haproxy=2.6.\*
#init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

#back up copy of default config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.org

#edit haproxy config
sudo echo -e "
frontend appname 
\tmode http
\tbind *:80
\tdefault_backend web_servers
backend web_servers
\tbalance roundrobin
\toption forwardfor
\tserver 107478-web-01 54.236.56.164:80 check
\tserver 107478-web-02 54.90.17.105:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

#verify config syntax of the configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
