#!/usr/bin/env bash
#script to fix nginx error to serve on port 80
#instead of port 8080 
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/ ipv6only=on;/;/' /etc/nginx/sites-available/default
sudo service nginx stop
sudo service nginx start
