#!/usr/bin/env bash
#script to fix nginx error to serve on port 80
#instead of port 8080 
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:80 default_server;/' /etc/nginx/sites-available/default
service nginx restart