#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits:
# Ctrl-C (SIGINT), kill (SIGTERM), and ctrl-| (SIGQUIT)
echo $$ >> /var/run/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
