#!/usr/bin/env bash
# script that fixes the container so that Nginx is running as the nginx user
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 777 /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx restart
